services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  migrate:
    build: .
    command: alembic upgrade head
    depends_on:
      - db
    restart: "no"

  web:
    image: isaogzzz/wallpaper-ai:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "${SERVER_PORT}:80"
    depends_on:
      - db
      - migrate


volumes:
  postgres_data: