"""empty message

Revision ID: 07124433ba1c
Revises: aa139eecad7b
Create Date: 2024-10-21 19:08:14.398819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07124433ba1c'
down_revision: Union[str, None] = 'aa139eecad7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leroymerlin_items', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
