"""empty message

Revision ID: 0a189ff0df0c
Revises: faf323784b03
Create Date: 2024-10-21 17:35:01.678768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a189ff0df0c'
down_revision: Union[str, None] = 'faf323784b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leroymerlin_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leroymerlin_items_id'), 'leroymerlin_items', ['id'], unique=False)
    op.create_index(op.f('ix_leroymerlin_items_url'), 'leroymerlin_items', ['url'], unique=False)
    op.drop_index('ix_wallpapers_id', table_name='wallpapers')
    op.drop_index('ix_wallpapers_url', table_name='wallpapers')
    op.drop_table('wallpapers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallpapers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wallpapers_pkey')
    )
    op.create_index('ix_wallpapers_url', 'wallpapers', ['url'], unique=False)
    op.create_index('ix_wallpapers_id', 'wallpapers', ['id'], unique=False)
    op.drop_index(op.f('ix_leroymerlin_items_url'), table_name='leroymerlin_items')
    op.drop_index(op.f('ix_leroymerlin_items_id'), table_name='leroymerlin_items')
    op.drop_table('leroymerlin_items')
    # ### end Alembic commands ###
