"""empty message

Revision ID: 3748057e2c5d
Revises: 5a3a11a984a3
Create Date: 2024-10-24 00:10:46.748094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3748057e2c5d'
down_revision: Union[str, None] = '5a3a11a984a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('uuid', sa.UUID(), nullable=False))
    op.alter_column('leroymerlin_items', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leroymerlin_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leroymerlin_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('leroymerlin_items', 'product_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_leroymerlin_items_url'), 'leroymerlin_items', ['url'], unique=False)
    op.drop_column('leroymerlin_items', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('leroymerlin_items', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('leroymerlin_items', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_leroymerlin_items_url'), table_name='leroymerlin_items')
    op.alter_column('leroymerlin_items', 'product_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leroymerlin_items', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('leroymerlin_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leroymerlin_items', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leroymerlin_items', 'uuid')
    # ### end Alembic commands ###
