"""empty message

Revision ID: 79a53e6deb41
Revises: e528ecb38ebc
Create Date: 2024-10-22 16:06:05.286611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a53e6deb41'
down_revision: Union[str, None] = 'e528ecb38ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('price_type', sa.String(), nullable=True))
    op.add_column('leroymerlin_items', sa.Column('product_type', sa.String(), nullable=True))

    # Alter the column with a cast
    op.alter_column(
        'leroymerlin_items',
        'price',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using='price::float'  # Specify how to cast the existing values
    )

    op.drop_column('leroymerlin_items', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('leroymerlin_items', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('leroymerlin_items', 'product_type')
    op.drop_column('leroymerlin_items', 'price_type')
    # ### end Alembic commands ###
