"""empty message

Revision ID: e528ecb38ebc
Revises: 07124433ba1c
Create Date: 2024-10-21 19:17:26.582750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e528ecb38ebc'
down_revision: Union[str, None] = '07124433ba1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leroymerlin_items', 'page_number')
    # ### end Alembic commands ###
