"""empty message

Revision ID: ef1d3edf83be
Revises: 1bd120ff700a
Create Date: 2024-10-22 17:03:40.407846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1d3edf83be'
down_revision: Union[str, None] = '1bd120ff700a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leroymerlin_items', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
