"""empty message

Revision ID: f7d156579dc2
Revises: 3748057e2c5d
Create Date: 2024-10-24 11:12:49.829778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d156579dc2'
down_revision: Union[str, None] = '3748057e2c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leroymerlin_items', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leroymerlin_items', 'page')
    # ### end Alembic commands ###
